### ISSUE TITLE
About mol.yml

### ISSUE THREAD

**Issue by xuezhen-liu** [Layne-Huang/PMDM#1]
I can't find the mol.yml file when installing the environment

**Comment by Layne-Huang** [comment]
Hi,

Sorry for the missing environment file. We have uploaded the mol.yaml. You could use it to install the virtual env for PMDM.

**Comment by lllxxxzzzz** [comment]
Thank you very much and I wish you all the best in your work.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Layne-Huang/PMDM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月5日(星期二) 凌晨4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Layne-Huang/PMDM] About mol.yml (Issue #1)





 
Hi,
 
Sorry for the missing environment file. We have uploaded the mol.yaml. You could use it to install the virtual env for PMDM.

**Comment by lllxxxzzzz** [comment]
Hello, I encountered a small issue during the training process. It seems that line 17 in the train.py file attempts to import a function named get_model from models.epsnet, but  I couldn't locate the models/epsnet.py file. Could you kindly verify if the file is missing? Thank you very much for your assistance.
