### ISSUE TITLE
Bugs in sample_linker.py

### ISSUE THREAD

**Issue by FeilongWuHaa** [Layne-Huang/PMDM#11]
Hi，author,

**1. wrong checkpoint name** 
when I tried to generate linker for custom pocket and molecule with command:
"
python -u sample_linker.py \
  --ckpt 500.pt \
  --pdb_path 3WZE/pocket.pdb \
  --mol_file 3WZE/3wze-mol.sdf \
  --mask 0 1 2 3 4 5 6 7 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32\
  --num_atom 4 \
  --num_samples 100 \
  --sampling_type generalized \
  --batch_size 32
"

but I got a error:
"
_Traceback (most recent call last):
  File "/home/PMDM/sample_linker.py", line 293, in <module>
    data_list,_ = construct_dataset_pocket(num_samples*1,batch_size,dataset_info,num_points,None,start_linker,None,
  File "/home/PMDM/utils/sample.py", line 154, in construct_dataset_pocket
    atom_type_linker = torch.cat([start_linker['linker_atom_type'], atom_type])
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 10 but got size 8 for tensor number 1 in the list._
"

if I rename the checkpoint to "500_pocket.pt", this bug have been fixed.

**2. missing QVinaDockingTask in sample_linker.py**
QVinaDockingTask.from_generated_data(protein_filename,gmol,protein_root) line 391.

**Comment by Layne-Huang** [comment]
Thanks for your feedback. 

1. I have revised the bug of sample_linker.py.
2. The QVinaDockingTask file exits in evaluation/docking.py. I suggest you comment this code since it is time consuming to calculate the vina score. Instead, you could evaluate them independently.

**Comment by FeilongWuHaa** [comment]
Thank you @Layne-Huang

**Comment by FeilongWuHaa** [comment]
Hi， 

by, your new version sample_linker.py files, when I tried to generate linker for custom pocket and molecule with command:
"
_python -u sample_linker.py
--ckpt 500.pt
--pdb_path 3WZE/pocket.pdb
--mol_file 3WZE/3wze-mol.sdf
--mask 0 1 2 3 4 5 6 7 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
--num_atom 4
--num_samples 100
--sampling_type generalized
--batch_size 32
"

there is not any molecule gengeraed, and I get an error of Open Babel  and Vina:
"
_generated smile: [C][C][C][C][N]C([N])=O
largest generated smile part: [C][C][C][C][N]C([N])=O
Generate SA score: 0.39
Generate QED score: 0.44795408144569576
Generate logP: -0.4310400000000001
Generate Lipinski: 5
[b'1 molecule converted\n', b'/bin/bash: line 10: ./qvina2.1: No such file or directory\n', b'==============================\n', b'*** Open Babel Error  in OpenAndSetFormat\n', b'  Cannot open bzkdjhxnzncstkznbnpmukvmuncykr_ligand_out.pdbqt\n', b'0 molecules converted\n']
[Error] Vina output error: /home/PMDM/tmp/bzkdjhxnzncstkznbnpmukvmuncykr_ligand_out.sdf
'NoneType' object is not subscriptable_
"

**for vina “./qvina2.1: No such file or directory”， it need put the qvina in the ./tmp foler.**
**Then all codes run well.**

But, the generate molecule is quit small, and It is only the part of linker.
How can I get the gennerated whole molecules with fragments?

**Comment by FeilongWuHaa** [comment]
It works now, thanks.
