### ISSUE TITLE
Code Issue

### ISSUE THREAD

**Issue by HITzhongyu** [Layne-Huang/PMDM#17]
Hi，Layne-Huang
       Thank you very much for your work, but while reading the code, at line 155 of the utils/protein_ligand.py file, the code reads as follows, 
      `def to_dict_atom_cutoff(self, ligand_pos, cutoff):`
and I would like to know why your code sets cutoff to 8 here, is this a priori knowledge?

**Comment by Layne-Huang** [comment]
It is set to get a smaller protein pocket which make it calculate more efficiently. You can also try other threshold like 10A or 20A.
