### ISSUE TITLE
Missing File in Training Process

### ISSUE THREAD

**Issue by xuezhen-liu** [Layne-Huang/PMDM#2]
Hello, I encountered a small issue during the training process. It seems that line 17 in the train.py file attempts to import a function named get_model from models.epsnet, but I couldn't locate the models/epsnet.py file. Could you kindly verify if the file is missing? Thank you very much for your assistance.

**Comment by Layne-Huang** [comment]
Thank you su much for pointing it out. We have uploaded the corresponding file which contains the `get_model` function. Fell free to reach out to me if you have further questions.
