### ISSUE TITLE
No matching distribution found for mkl==2017.0.3

### ISSUE THREAD

**Issue by CADDfarmer** [Layne-Huang/PMDM#20]
Hello,

Thank you for your excellent work. I got an error when I built the environment of adt.

ERROR: Could not find a version that satisfies the requirement mkl==2017.0.3 (from versions: 2018.0.0, 2018.0.3, 2019.0, 2021.1.1, 2021.2.0, 2021.3.0, 2021.4.0, 2022.0.1, 2022.0.2, 2022.1.0, 2022.2.0, 2022.2.1, 2023.0.0, 2023.1.0, 2023.2.0, 2024.0.0, 2024.1.0)
ERROR: No matching distribution found for mkl==2017.0.3

"2017.0.3" seems is a old version and I can't download it from pypi. Also, I can't find a website to get mkl-2017.0.3. So, my question is that:

Can I use a newer version? Such as 2018.0.0.

And when I checked the package list in the adt environment by "conda list", I found that mkl was in the list - mkl-2022.0.1. So, here is my question:

Is there any problem if I ues the newer mkl of 2022.0.1? 
Is it necessary for this environment to use the version of 2017.0.3?

**Comment by Layne-Huang** [comment]
I think it should be fine.
