### ISSUE TITLE
How to generate bond

### ISSUE THREAD

**Issue by HITzhongyu** [Layne-Huang/PMDM#26]
Hi，Layne-Huang
Thank you very much for your work, and I want to know in your work, only generate the atom and atom coordinate, and use the 'open babel' tools to generate the final drug stucture? I wonder how to generate the bond?
thanks!
Zhongyu

**Comment by HITzhongyu** [comment]
I also have  another questios
in your `MDM_pocket_coor_shared.py` line 374-378, I want to know why here ligand atom add context?
Thanks!
Zhongyu

**Comment by Layne-Huang** [comment]
Hi,

We build the bonds according to the distance and types of the atoms. We have a directory to store the distance of different chemical bonds, for example, C-C. If the distance of the generated two carbon atoms is shorter than the stored value, then we build the C-C chemical bond.
