### ISSUE TITLE
There is no prepare_receptor4.py in the evaluation/ directory

### ISSUE THREAD

**Issue by ReddysLab** [Layne-Huang/PMDM#30]
There is no prepare_receptor4.py in the evaluation/ directory. It is required for pdbqt conversion, and required by prepare_qdbqt.py

**Comment by Layne-Huang** [comment]
Hi,

You need to install adt env which includes this script.

**Comment by ReddysLab** [comment]
Hello - we did this already. I don't understand how the env_adt.yml can include this script? Is it part of specific package?
Thanks.
