### ISSUE TITLE
installing question

### ISSUE THREAD

**Issue by DM0815** [Layne-Huang/PMDM#34]
When conduct  '''conda env create -f mol.yml'', reminds that errors as follows:
  Downloading scikit_learn-1.4.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting threadpoolctl==3.4.0 (from -r /home/dmeng/protein/PMDM/condaenv.gp90ww7m.requirements.txt (line 24))
  Downloading threadpoolctl-3.4.0-py3-none-any.whl.metadata (13 kB)

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement torch-cluster==1.6.3+pt21cu118 (from versions: 0.1.1, 0.2.3, 0.2.4, 1.0.1, 1.0.3, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3a1, 1.4.3, 1.4.4, 1.4.5, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.6.0, 1.6.1, 1.6.2, 1.6.3)
ERROR: No matching distribution found for torch-cluster==1.6.3+pt21cu118
                                                               failed

CondaEnvException: Pip failed
 Can you give some suggestions. Thanks.

**Comment by Layne-Huang** [comment]
Hi,

You could skip this step and install pyg by this link[https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html](url)

**Comment by DM0815** [comment]
> Hi,
> 
> You could skip this step and install pyg by this link[https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html](url)

Got it. Thanks

**Comment by DM0815** [comment]
> Hi,
> 
> You could skip this step and install pyg by this link[https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html](url)

I'm sorry to bother you. I  install pyg seperately.  When  I conduct your  example command. It reminds that     from torch._C import *  # noqa: F403
ImportError:*3/envs/mol/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so: undefined symbol: cudaLaunchKernelExC, version libcudart.so.11.0.  I want to know if there are other methods to install env file

**Comment by Layne-Huang** [comment]
Hi,

Pls install the pyg according to your pytorch and cuda version

**Comment by DM0815** [comment]
> Hi,
> 
> Pls install the pyg according to your pytorch and cuda version

I think they match well. and it's same to your env file. I just simply commented out the packages related to pyg inside your environment file, and installed pyg separately immediately "pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.1.0+cu118.html" 
after first executing your command "conda env create -f mol.yml",
Then it reminds errors as above.  pip list as follows
[requirements.txt](https://github.com/user-attachments/files/16595856/requirements.txt)

**Comment by Layne-Huang** [comment]
This error is caused by the pytorch. You did not install pytorch successfully. You should check your cuda version and the env path.

**Comment by Linzy19** [comment]
I also encountered the same problem, how can I solve it ？

**Comment by Linzy19** [comment]
My nvcc -V is 11.8, system is ubtanuc, but direct "conda env create -f mol.yml" is the same problem

**Comment by DM0815** [comment]
> My nvcc -V is 11.8, system is ubtanuc, but direct "conda env create -f mol.yml" is the same problem
I think you can read my answer above carefully and comment out the five pyg-related packages in mol.yml file to install them separately after "conda env create -f mol.yml"

**Comment by mchakra8** [comment]
I also ran into multiple issues with getting all the packages in this environment to work correctly. (Issues included `undefined symbol: cudaLaunchKernelExC, version libcudart.so.11.0` as well as `OSError: /lib64/libm.so.6: version 'GLIBC_2.29' not found`). Below is the environment (*.yml) that I was finally able to get working. Hopefully, this will be useful to others.

```
name: pmdm
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - acpype=2022.7.21=pyhd8ed1ab_1
  - ambertools=22.4=py39h804d063_0
  - arpack=3.7.0=hdefa2d7_2
  - blas=1.0=mkl
  - boost=1.78.0=py39hda80f44_5
  - boost-cpp=1.78.0=h2c5509c_4
  - bottleneck=1.3.7=py39ha9d4c09_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py39h6a678d5_7
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.4=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cffi=1.17.0=py39h49a4b6b_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py39hdb19cb5_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudatoolkit-dev=11.7.0=h1de0b5d_6
  - cudnn=8.9.7.29=hbc23b4c_3
  - curl=8.5.0=hdbd6064_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=3.0.10=py39h5eee18b_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_hc118613_108
  - filelock=3.13.1=py39h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.53.1=py39hcd6043d_0
  - freetype=2.12.1=h4a9f257_0
  - gdbm=1.18=hd4cb3f1_4
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - greenlet=3.0.1=py39h6a678d5_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.2=nompi_h4df4325_101
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.8=pyhd8ed1ab_0
  - importlib-resources=6.1.1=pyhd8ed1ab_0
  - importlib_resources=6.1.1=py39h06a4308_1
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=8.5.0=h251f7ec_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.78.4=hdc74915_0
  - libgomp=13.2.0=h807b86a_5
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libnetcdf=4.9.1=nompi_h34a3ff0_101
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libsqlite=3.45.2=h2797004_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.6=h232c23b_1
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.5=py39hd1e30aa_0
  - matplotlib-base=3.9.2=py39h0565ad7_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - netcdf-fortran=4.6.0=nompi_heb5813c_103
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py39h06a4308_0
  - numexpr=2.8.7=py39h85018f9_0
  - numpy=1.23.5=py39hf6e8229_1
  - numpy-base=1.23.5=py39h060ed82_1
  - openbabel=3.1.1=py39h2d01fe1_9
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.3.1=hb9d3cd8_3
  - packaging=23.2=py39h06a4308_0
  - packmol=20.010=h86c2bf4_0
  - pandas=2.1.3=py39hddac248_0
  - parmed=3.4.4=py39h227be39_0
  - pcre2=10.42=hebb0a14_0
  - perl=5.34.0=h5eee18b_2
  - pillow=10.2.0=py39h5eee18b_0
  - pip=23.3.1=py39h06a4308_0
  - pixman=0.43.2=h59595ed_0
  - pycairo=1.23.0=py39hd1222b9_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.18=h0755675_1_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.9=4_cp39
  - pytorch=2.1.0=py3.9_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py39h06a4308_0
  - pyyaml=6.0.1=py39h5eee18b_0
  - qhull=2020.2=h434a139_5
  - rdkit=2022.09.1=py39hb00a813_2
  - readline=8.2=h5eee18b_0
  - reportlab=3.5.67=py39hfdd840d_1
  - requests=2.32.3=pyhd8ed1ab_0
  - setuptools=68.2.2=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlalchemy=2.0.25=py39h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.1.0=py39_cu121
  - torchtriton=2.1.0=py39
  - torchvision=0.16.0=py39_cu121
  - typing-extensions=4.9.0=py39h06a4308_1
  - typing_extensions=4.9.0=py39h06a4308_1
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py39hd1e30aa_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - wheel=0.41.2=py39h06a4308_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.17.0=py39h06a4308_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.22.0=py39h6e5214e_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - amberlite==22.0
      - amberutils==21.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - biopython==1.83
      - easydict==1.13
      - einops==0.8.0
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - joblib==1.4.2
      - mmpbsa-py==16.0
      - multidict==6.0.5
      - packmol-memgen==1.2.3rc0
      - pdb4amber==22.0
      - psutil==6.0.0
      - pyg-lib==0.3.1+pt21cu121
      - pyparsing==3.1.4
      - pytraj==2.0.6
      - sander==22.0
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - threadpoolctl==3.5.0
      - torch-cluster==1.6.3+pt21cu121
      - torch-geometric==2.4.0
      - torch-scatter==2.1.2+pt21cu121
      - torch-sparse==0.6.18+pt21cu121
      - torch-spline-conv==1.2.2+pt21cu121
      - tqdm==4.66.5
      - yarl==1.9.4
prefix: /home/user/miniforge3/envs/pmdm
```

**Comment by Linzy19** [comment]
> I also ran into multiple issues with getting all the packages in this environment to work correctly. (Issues included `undefined symbol: cudaLaunchKernelExC, version libcudart.so.11.0` as well as `OSError: /lib64/libm.so.6: version 'GLIBC_2.29' not found`). Below is the environment (*.yml) that I was finally able to get working. Hopefully, this will be useful to others.
> 
> ```
> name: pmdm
> channels:
>   - pytorch
>   - nvidia
>   - defaults
>   - conda-forge
> dependencies:
>   - _libgcc_mutex=0.1=conda_forge
>   - _openmp_mutex=4.5=2_gnu
>   - acpype=2022.7.21=pyhd8ed1ab_1
>   - ambertools=22.4=py39h804d063_0
>   - arpack=3.7.0=hdefa2d7_2
>   - blas=1.0=mkl
>   - boost=1.78.0=py39hda80f44_5
>   - boost-cpp=1.78.0=h2c5509c_4
>   - bottleneck=1.3.7=py39ha9d4c09_0
>   - brotli=1.0.9=h5eee18b_7
>   - brotli-bin=1.0.9=h5eee18b_7
>   - brotli-python=1.0.9=py39h6a678d5_7
>   - bzip2=1.0.8=hd590300_5
>   - c-ares=1.19.1=h5eee18b_0
>   - ca-certificates=2024.7.4=hbcca054_0
>   - cairo=1.18.0=h3faef2a_0
>   - certifi=2024.7.4=pyhd8ed1ab_0
>   - cffi=1.17.0=py39h49a4b6b_0
>   - charset-normalizer=3.3.2=pyhd8ed1ab_0
>   - contourpy=1.2.0=py39hdb19cb5_0
>   - cuda-cudart=12.1.105=0
>   - cuda-cupti=12.1.105=0
>   - cuda-libraries=12.1.0=0
>   - cuda-nvrtc=12.1.105=0
>   - cuda-nvtx=12.1.105=0
>   - cuda-opencl=12.4.127=0
>   - cuda-runtime=12.1.0=0
>   - cuda-version=11.8=h70ddcb2_3
>   - cudatoolkit=11.8.0=h4ba93d1_13
>   - cudatoolkit-dev=11.7.0=h1de0b5d_6
>   - cudnn=8.9.7.29=hbc23b4c_3
>   - curl=8.5.0=hdbd6064_0
>   - cycler=0.11.0=pyhd3eb1b0_0
>   - cython=3.0.10=py39h5eee18b_0
>   - expat=2.5.0=h6a678d5_0
>   - ffmpeg=4.3=hf484d3e_0
>   - fftw=3.3.10=nompi_hc118613_108
>   - filelock=3.13.1=py39h06a4308_0
>   - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
>   - font-ttf-inconsolata=2.001=hcb22688_0
>   - font-ttf-source-code-pro=2.030=hd3eb1b0_0
>   - font-ttf-ubuntu=0.83=h8b1ccd4_0
>   - fontconfig=2.14.2=h14ed4e7_0
>   - fonts-anaconda=1=h8fa9717_0
>   - fonts-conda-ecosystem=1=hd3eb1b0_0
>   - fonttools=4.53.1=py39hcd6043d_0
>   - freetype=2.12.1=h4a9f257_0
>   - gdbm=1.18=hd4cb3f1_4
>   - glib=2.78.4=h6a678d5_0
>   - glib-tools=2.78.4=h6a678d5_0
>   - gmp=6.2.1=h295c915_3
>   - gmpy2=2.1.2=py39heeb90bb_0
>   - gnutls=3.6.15=he1e5248_0
>   - greenlet=3.0.1=py39h6a678d5_0
>   - h2=4.1.0=pyhd8ed1ab_0
>   - hdf4=4.2.15=h9772cbc_5
>   - hdf5=1.12.2=nompi_h4df4325_101
>   - hpack=4.0.0=pyh9f0ad1d_0
>   - hyperframe=6.0.1=pyhd8ed1ab_0
>   - icu=73.2=h59595ed_0
>   - idna=3.8=pyhd8ed1ab_0
>   - importlib-resources=6.1.1=pyhd8ed1ab_0
>   - importlib_resources=6.1.1=py39h06a4308_1
>   - intel-openmp=2023.1.0=hdb19cb5_46306
>   - jinja2=3.1.4=pyhd8ed1ab_0
>   - jpeg=9e=h5eee18b_1
>   - kiwisolver=1.4.4=py39h6a678d5_0
>   - krb5=1.20.1=h143b758_1
>   - lame=3.100=h7b6447c_0
>   - lcms2=2.12=h3be6417_0
>   - ld_impl_linux-64=2.38=h1181459_1
>   - lerc=3.0=h295c915_0
>   - libaec=1.1.3=h59595ed_0
>   - libblas=3.9.0=1_h86c2bf4_netlib
>   - libbrotlicommon=1.0.9=h5eee18b_7
>   - libbrotlidec=1.0.9=h5eee18b_7
>   - libbrotlienc=1.0.9=h5eee18b_7
>   - libcublas=12.1.0.26=0
>   - libcufft=11.0.2.4=0
>   - libcufile=1.9.1.3=0
>   - libcurand=10.3.5.147=0
>   - libcurl=8.5.0=h251f7ec_0
>   - libcusolver=11.4.4.55=0
>   - libcusparse=12.0.2.55=0
>   - libdeflate=1.17=h5eee18b_1
>   - libedit=3.1.20230828=h5eee18b_0
>   - libev=4.33=h7f8727e_1
>   - libffi=3.4.4=h6a678d5_0
>   - libgcc-ng=13.2.0=h807b86a_5
>   - libgfortran-ng=13.2.0=h69a702a_5
>   - libgfortran5=13.2.0=ha4646dd_5
>   - libglib=2.78.4=hdc74915_0
>   - libgomp=13.2.0=h807b86a_5
>   - libiconv=1.17=hd590300_2
>   - libidn2=2.3.4=h5eee18b_0
>   - libjpeg-turbo=2.0.0=h9bf148f_0
>   - liblapack=3.9.0=5_h92ddd45_netlib
>   - libnetcdf=4.9.1=nompi_h34a3ff0_101
>   - libnghttp2=1.57.0=h2d74bed_0
>   - libnpp=12.0.2.50=0
>   - libnsl=2.0.1=hd590300_0
>   - libnvjitlink=12.1.105=0
>   - libnvjpeg=12.1.1.14=0
>   - libpng=1.6.39=h5eee18b_0
>   - libsqlite=3.45.2=h2797004_0
>   - libssh2=1.10.0=hdbd6064_2
>   - libstdcxx-ng=13.2.0=h7e041cc_5
>   - libtasn1=4.19.0=h5eee18b_0
>   - libtiff=4.5.1=h6a678d5_0
>   - libunistring=0.9.10=h27cfd23_0
>   - libuuid=2.38.1=h0b41bf4_0
>   - libwebp-base=1.3.2=h5eee18b_0
>   - libxcb=1.15=h7f8727e_0
>   - libxcrypt=4.4.36=hd590300_1
>   - libxml2=2.12.6=h232c23b_1
>   - libzip=1.10.1=h2629f0a_3
>   - libzlib=1.2.13=hd590300_5
>   - llvm-openmp=14.0.6=h9e868ea_0
>   - lz4-c=1.9.4=h6a678d5_0
>   - markupsafe=2.1.5=py39hd1e30aa_0
>   - matplotlib-base=3.9.2=py39h0565ad7_0
>   - mkl=2023.1.0=h213fc3f_46344
>   - mkl-service=2.4.0=py39h5eee18b_1
>   - mkl_fft=1.3.8=py39h5eee18b_0
>   - mkl_random=1.2.4=py39hdb19cb5_0
>   - mpc=1.1.0=h10f8cd9_1
>   - mpfr=4.0.2=hb69a4c5_1
>   - mpmath=1.3.0=py39h06a4308_0
>   - munkres=1.1.4=py_0
>   - ncurses=6.4=h6a678d5_0
>   - netcdf-fortran=4.6.0=nompi_heb5813c_103
>   - nettle=3.7.3=hbbd107a_1
>   - networkx=3.1=py39h06a4308_0
>   - numexpr=2.8.7=py39h85018f9_0
>   - numpy=1.23.5=py39hf6e8229_1
>   - numpy-base=1.23.5=py39h060ed82_1
>   - openbabel=3.1.1=py39h2d01fe1_9
>   - openh264=2.1.1=h4ff587b_0
>   - openjpeg=2.4.0=h3ad879b_0
>   - openssl=3.3.1=hb9d3cd8_3
>   - packaging=23.2=py39h06a4308_0
>   - packmol=20.010=h86c2bf4_0
>   - pandas=2.1.3=py39hddac248_0
>   - parmed=3.4.4=py39h227be39_0
>   - pcre2=10.42=hebb0a14_0
>   - perl=5.34.0=h5eee18b_2
>   - pillow=10.2.0=py39h5eee18b_0
>   - pip=23.3.1=py39h06a4308_0
>   - pixman=0.43.2=h59595ed_0
>   - pycairo=1.23.0=py39hd1222b9_0
>   - pycparser=2.22=pyhd8ed1ab_0
>   - pysocks=1.7.1=py39h06a4308_0
>   - python=3.9.18=h0755675_1_cpython
>   - python-dateutil=2.8.2=pyhd3eb1b0_0
>   - python-tzdata=2023.3=pyhd3eb1b0_0
>   - python_abi=3.9=4_cp39
>   - pytorch=2.1.0=py3.9_cuda12.1_cudnn8.9.2_0
>   - pytorch-cuda=12.1=ha16c6d3_5
>   - pytorch-mutex=1.0=cuda
>   - pytz=2023.3.post1=py39h06a4308_0
>   - pyyaml=6.0.1=py39h5eee18b_0
>   - qhull=2020.2=h434a139_5
>   - rdkit=2022.09.1=py39hb00a813_2
>   - readline=8.2=h5eee18b_0
>   - reportlab=3.5.67=py39hfdd840d_1
>   - requests=2.32.3=pyhd8ed1ab_0
>   - setuptools=68.2.2=py39h06a4308_0
>   - six=1.16.0=pyhd3eb1b0_1
>   - sqlalchemy=2.0.25=py39h5eee18b_0
>   - sqlite=3.41.2=h5eee18b_0
>   - sympy=1.12=py39h06a4308_0
>   - tbb=2021.8.0=hdb19cb5_0
>   - tk=8.6.13=noxft_h4845f30_101
>   - torchaudio=2.1.0=py39_cu121
>   - torchtriton=2.1.0=py39
>   - torchvision=0.16.0=py39_cu121
>   - typing-extensions=4.9.0=py39h06a4308_1
>   - typing_extensions=4.9.0=py39h06a4308_1
>   - tzdata=2024a=h04d1e81_0
>   - unicodedata2=15.1.0=py39hd1e30aa_0
>   - urllib3=2.2.2=pyhd8ed1ab_1
>   - wheel=0.41.2=py39h06a4308_0
>   - xorg-kbproto=1.0.7=h7f98852_1002
>   - xorg-libice=1.1.1=hd590300_0
>   - xorg-libsm=1.2.4=h7391055_0
>   - xorg-libx11=1.8.9=h8ee46fc_0
>   - xorg-libxext=1.3.4=h0b41bf4_2
>   - xorg-libxrender=0.9.11=hd590300_0
>   - xorg-libxt=1.3.0=hd590300_1
>   - xorg-renderproto=0.11.1=h7f98852_1002
>   - xorg-xextproto=7.3.0=h0b41bf4_1003
>   - xorg-xproto=7.0.31=h27cfd23_1007
>   - xz=5.4.6=h5eee18b_0
>   - yaml=0.2.5=h7b6447c_0
>   - zipp=3.17.0=py39h06a4308_0
>   - zlib=1.2.13=hd590300_5
>   - zstandard=0.22.0=py39h6e5214e_0
>   - zstd=1.5.5=hc292b87_0
>   - pip:
>       - aiohappyeyeballs==2.4.0
>       - aiohttp==3.10.5
>       - aiosignal==1.3.1
>       - amberlite==22.0
>       - amberutils==21.0
>       - async-timeout==4.0.3
>       - attrs==24.2.0
>       - biopython==1.83
>       - easydict==1.13
>       - einops==0.8.0
>       - frozenlist==1.4.1
>       - fsspec==2024.6.1
>       - joblib==1.4.2
>       - mmpbsa-py==16.0
>       - multidict==6.0.5
>       - packmol-memgen==1.2.3rc0
>       - pdb4amber==22.0
>       - psutil==6.0.0
>       - pyg-lib==0.3.1+pt21cu121
>       - pyparsing==3.1.4
>       - pytraj==2.0.6
>       - sander==22.0
>       - scikit-learn==1.5.1
>       - scipy==1.13.1
>       - threadpoolctl==3.5.0
>       - torch-cluster==1.6.3+pt21cu121
>       - torch-geometric==2.4.0
>       - torch-scatter==2.1.2+pt21cu121
>       - torch-sparse==0.6.18+pt21cu121
>       - torch-spline-conv==1.2.2+pt21cu121
>       - tqdm==4.66.5
>       - yarl==1.9.4
> prefix: /home/user/miniforge3/envs/pmdm
> ```

how about your torch and cuda version to install this env

**Comment by mchakra8** [comment]
> how about your torch and cuda version to install this env

I am not sure I understand what you mean. Torch and CUDA are included within the environment:

```
  - pytorch=2.1.0=py3.9_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
 ```

```
Python 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:33:10)
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch; print(torch.__version__)
2.1.0
>>> import torch; print(torch.version.cuda)
12.1
```

**Comment by laee10** [comment]
> > 你的 torch 和 cuda 版本如何安装此环境
> 
> 我不确定我理解你的意思。Torch 和 CUDA 包含在环境中：
> 
> ```
>   - pytorch=2.1.0=py3.9_cuda12.1_cudnn8.9.2_0
>   - pytorch-cuda=12.1=ha16c6d3_5
> ```
> 
> ```
> Python 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:33:10)
> [GCC 12.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch; print(torch.__version__)
> 2.1.0
> >>> import torch; print(torch.version.cuda)
> 12.1
> ```

What is your computer operating system?

**Comment by laee10** [comment]
I am currently using Microsoft Windows 11 Home Edition, version 10.0.22631, with CUDA version 12.3. I have tried updating Conda and incrementally installing dependencies, but I still cannot successfully configure the environment. I suspect that some of the dependency packages or versions might be incompatible.

**Comment by laee10** [comment]
As a beginner in coding, I have just entered the field of utilizing artificial intelligence for drug design. This presents a new challenge for me, and while following the instructions in the README.md for setting up the environment, I encountered some issues. When I attempted to clone the Conda environment using the mol.yml file, I received the following error message as shown in the attached picture。
<img width="674" alt="联想截图_20240906223039" src="https://github.com/user-attachments/assets/3b293e81-e633-4440-aaab-0a98e61efc93">
<img width="474" alt="联想截图_20240906223012" src="https://github.com/user-attachments/assets/135a8aca-c8d1-4c71-8f39-063271c766b5">

**Comment by msinclair-py** [comment]
@mchakra8 You are my savior. 

For anyone else having difficulty installing the dependencies: the pip portion does not understand any of the pyg/torch-geometric dependencies as they are very version-specific. I took the yml file above and only had conda install the conda portions and manually installed the rest via pip but it did work for me in the end.

**Comment by mchakra8** [comment]
> @mchakra8 You are my savior.
> 
> For anyone else having difficulty installing the dependencies: the pip portion does not understand any of the pyg/torch-geometric dependencies as they are very version-specific. I took the yml file above and only had conda install the conda portions and manually installed the rest via pip but it did work for me in the end.

Glad you found it helpful! 🙂 I had to spend quite a bit of time troubleshooting the dependency issues.

**Comment by nfloquet** [comment]
after many many tests and following the comments in this list, i just gave up, too much problems of dependencies ...

**Comment by Layne-Huang** [comment]
Dear all,

Sorry for the inconvenience of the previous install files. I have uploaded the mol.yml file and the install guidelines, pls follow it to install the env. There should be no issue now.

Thanks!
