### ISSUE TITLE
cannot get date in Data preparation

### ISSUE THREAD

**Issue by Linzy19** [Layne-Huang/PMDM#35]
For test data in Binding MOAD, when I run the wget, it always shows a timeout, can you put this data set in Zenodo or update the wget address to make sure it's available

"""
wget http://www.bindingmoad.org/files/biou/every_part_a.zip
wget http://www.bindingmoad.org/files/biou/every_part_b.zip
wget http://www.bindingmoad.org/files/csv/every.csv
"""

**Comment by realfenston** [comment]
same issue here. Any suggestions?

**Comment by laee10** [comment]
[http://www.BindingMOAD.org This domain has expired. 
The webpage has been closed and I am unable to access the relevant data. Is there any other way or link for me to obtain the relevant dataset for training @Layne-Huang

**Comment by Layne-Huang** [comment]
Hi,

It works now!

**Comment by paulsonak** [comment]
BindingMOAD has been sunsetted and the website www.bindingMOAD.org doesn't work anymore: 

https://www.nature.com/articles/s41598-023-29996-w

Any recommendations?
