### ISSUE TITLE
Problem while creating the environment : "ess error: ERROR: Could not find a version that satisfies the requirement torch-cluster= ...

### ISSUE THREAD

**Issue by nfloquet** [Layne-Huang/PMDM#36]
despite having installed torch-cluster version properly i still got this error message .... could help plz ? 

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement torch-cluster==1.6.3+pt21cu118 (from versions: 0.1.1, 0.2.3, 0.2.4, 1.0.1, 1.0.3, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3a1, 1.4.3, 1.4.4, 1.4.5, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.6.0, 1.6.1, 1.6.2, 1.6.3)
ERROR: No matching distribution found for torch-cluster==1.6.3+pt21cu118

**Comment by maple0leaves** [comment]
You should install it separately
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv -f https://pytorch-geometric.com/whl/torch-2.1.0+cu118.html
pip install torch-geometric==2.4.0

<img width="339" alt="Snipaste_2024-09-28_16-48-15" src="https://github.com/user-attachments/assets/d8959e4a-9585-470d-83d0-cbd5fc347391">

**Comment by nfloquet** [comment]
thanks to your comments i progressed in installing all but executing a first test i got a new error : 

 python -u sample_for_pdb.py --ckpt ./check.out --pdb_path ./pdbs/receptor.pdb --num_atom 25 --num_samples 10 --sampling_type generalized
sh: 1: module: not found
Traceback (most recent call last):
  File "/home/nicolas/PROGRAMMES/PMDM/PMDM/sample_for_pdb.py", line 13, in <module>
    from evaluation import *
  File "/home/nicolas/PROGRAMMES/PMDM/PMDM/evaluation/__init__.py", line 1, in <module>
    from .evaluation_metrics import *
  File "/home/nicolas/PROGRAMMES/PMDM/PMDM/evaluation/evaluation_metrics.py", line 7, in <module>
    import torch
  File "/home/nicolas/anaconda3/envs/mol/lib/python3.9/site-packages/torch/__init__.py", line 235, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/nicolas/anaconda3/envs/mol/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so: undefined symbol: cudaLaunchKernelExC, version libcudart.so.11.0

could you help ?

**Comment by maple0leaves** [comment]
![image](https://github.com/user-attachments/assets/add96b2d-c4f4-42f3-8202-7ee24a93604a)

you can see this issue,someone has the same problem.And for issues related to pyg packages, you can install them separately.

**Comment by nfloquet** [comment]
Ty, however, is there a chance to work with other versions of cuda ? 
Appears i have uptodate 12.6 , is it looking for 11.* ?

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Aug_14_10:10:22_PDT_2024
Cuda compilation tools, release 12.6, V12.6

**Comment by maple0leaves** [comment]
It's better to version match.

**Comment by Layne-Huang** [comment]
Dear all,

Sorry for the inconvenience of the previous install files. I have uploaded the mol.yml file and the install guideline, pls follow it to install the env. There should be no issue now.

Thanks!
