### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (389x10 and 8x128)

### ISSUE THREAD

**Issue by Bigrock-dd** [Layne-Huang/PMDM#39]
I ran the command python -u train.py --config configs/crossdock_epoch.yml as instructed, but got this error ‘RuntimeError: mat1 and mat2 shapes cannot be multiplied (389x10 and 8x128)’. If it's not too much trouble for you, could you tell me what's wrong?

**Comment by Layne-Huang** [comment]
Hi,

Have you ever tried to change the arguments of crossdock_epoch.yml?

**Comment by DrugD** [comment]
代码写的太糟糕了，MDM_pocket_coor_shared.py 就不能把这个搞舒服点嘛？



    '''
        Atom numbers embedding
        '''
        if self.atom_num_emb:
            context = context + num_node_ctx

        ligand_atom_feature = self.ligand_encoder(
            node_attr=ligand_atom_type,
            pos=ligand_pos,
            batch=ligand_batch,
        ) + context
        # ligand_atom_feature = self.ligand_emblin(ligand_atom_type)+context
        # protein_atom_feature = self.protein_emblin(protein_atom_feature)
        ligand_atom_feature, protein_embeddings = self.atten_layer(ligand_atom_feature, protein_embeddings)
        # ligand_atom_feature = self.atten_layer(ligand_atom_feature, protein_embeddings)
        # ligand_atom_feature  = self.atten_layer(ligand_atom_feature, protein_atom_feature)

        pocket_atom = torch.cat([ligand_atom_feature, protein_embeddings], dim=0)
        pocket_pos = torch.cat([ligand_pos, protein_pos], dim=0)
        pocket_batch = torch.cat([ligand_batch, protein_batch])
        pocket_mask = torch.cat([linker_mask,torch.zeros(protein_pos.size(0), dtype=torch.bool).to(linker_mask.device)]) if linker_mask is not None else None



        if edge_index is None or edge_type is None or edge_length is None:
            full_bond_type = torch.ones(ligand_bond_index.size(1), dtype=torch.long).to(ligand_bond_index.device)

            # Construct local and global edges
            edge_index, edge_type = extend_graph_order_radius(
                num_nodes=N,
                pos=ligand_pos,
                edge_index=ligand_bond_index,
                edge_type=full_bond_type,
                batch=ligand_batch,
                order=self.config.edge_order,
                cutoff=self.config.cutoff,
                extend_order=extend_order,
                extend_radius=extend_radius,
                is_sidechain=is_sidechain,
            )
            edge_length = get_distance(ligand_pos, edge_index).unsqueeze(-1)  # (E, 1)
            ligand_bond_index = None #comment if fix the edge

        local_pocket_edge = get_edges(pocket_pos, pocket_batch, ligand_batch, self.config.cutoff, self.config.cutoff,ligand_bond_index) #ligand_bond_index
        global_pocket_edge = get_edges(pocket_pos, pocket_batch, ligand_batch, self.config.g_cutoff,
                                       self.config.g_cutoff)  # self.config.g_cutoff
        local_pocket_edge_length = get_distance(pocket_pos, local_pocket_edge).unsqueeze(-1)
        global_pocket_edge_length = get_distance(pocket_pos, global_pocket_edge).unsqueeze(-1)

        if ligand_bond_type is not None:
            local_edge_mask = is_local_edge(ligand_bond_type)
        else:
            local_edge_mask = is_radius_edge(edge_type)
        
        

        # Emb time_step
        # with the parameterization of NCSNv2
        # DDPM loss implicit handle the noise variance scale conditioning

        # if self.time_emb:
        #     # node2graph = ligand_batch
        #     node2graph = pocket_batch
        #     # edge2graph = node2graph.index_select(0, edge_index[0])
        #     global_edge2graph = node2graph.index_select(0, global_pocket_edge[0])
        #     g_temb_edge = temb.index_select(0, global_edge2graph)
        #     g_protein_edge = protein_ctx.index_select(0, global_edge2graph)
        #     # ptemb_edge = torch.cat([protein_edge,temb_edge],dim=1)
        #     g_ptemb_edge = g_protein_edge+g_temb_edge
        #     local_edge2graph = node2graph.index_select(0, local_pocket_edge[0])
        #     l_temb_edge = temb.index_select(0, local_edge2graph)
        #     l_protein_edge = protein_ctx.index_select(0, local_edge2graph)
        #     # ptemb_edge = torch.cat([protein_edge,temb_edge],dim=1)
        #     l_ptemb_edge = l_protein_edge+l_temb_edge

        # Encoding global

        # edge_attr_global = self.edge_encoder_global(
        #     edge_length=edge_length,
        #     edge_type=edge_type
        # )   # Embed edges
        edge_attr_global = self.edge_encoder_global(
            edge_length=global_pocket_edge_length,
            edge_type=None
        )  # Embed edges
        # if self.time_emb:
        #     # edge_attr_global += temb_edge
        #     edge_attr_global += g_ptemb_edge

        # # SphereNet
        # _,node_attr_global,_ = self.encoder_global(
        #     z=atom_type,
        #     pos=pos,
        #     batch=batch
        # )

        # # SchNet
        # # print(self.atom_type_input_dim)
        # node_attr_global,pos_attr_global = self.encoder_global(
        #     z=pocket_atom,
        #     r=pocket_pos,
        #     edge_index=global_pocket_edge,
        #     edge_length=global_pocket_edge_length,
        #     edge_attr=edge_attr_global,
        #     ligand_batch=ligand_batch,
        #     ctx=context,
        #     embed_node = False # default is True
        # )

        # EGNN
        node_attr_global, pos_attr_global = self.encoder_global(
            z=pocket_atom,
            pos=pocket_pos,
            edge_index=global_pocket_edge,
            edge_attr=edge_attr_global,
            batch=pocket_batch,
            ligand_batch=ligand_batch,
            context=context,
            linker_mask=pocket_mask
        )

        # Encoding local
        # edge_attr_local = self.edge_encoder_local(
        #     edge_length=edge_length,
        #     edge_type=edge_type
        # )   # Embed edges
        edge_attr_local = self.edge_encoder_local(
            edge_length=local_pocket_edge_length,
            edge_type=None
        )  # Embed edges
        # if self.time_emb:
        #     # edge_attr_local += temb_edge
        #     edge_attr_local += l_ptemb_edge

        # # GIN
        # node_attr_local = self.encoder_local(
        #     z=ligand_atom_type,
        #     edge_index=edge_index[:, local_edge_mask],
        #     edge_attr=edge_attr_local[local_edge_mask],
        # )

        # EGNN
        node_attr_local, pos_attr_local = self.encoder_local(
            z=pocket_atom,
            pos=pocket_pos,
            edge_index=local_pocket_edge,
            edge_attr=edge_attr_local,
            batch=pocket_batch,
            ligand_batch=ligand_batch,
            context=context,
            linker_mask=pocket_mask
        )

        # # Schnet
        # node_attr_local, pos_attr_local = self.encoder_local(
        #     z=pocket_atom,
        #     r=pocket_pos,
        #     edge_index=local_pocket_edge,
        #     edge_length=local_pocket_edge_length,
        #     edge_attr=edge_attr_local,
        #     ligand_batch=ligand_batch,
        #     ctx=context,
        #     embed_node = False # default is True
        # )

        node_score_global = self.grad_global_node_mlp(node_attr_global)
        node_score_local = self.grad_local_node_mlp(node_attr_local)

        if self.vae_context:
            return pos_attr_global, pos_attr_local, node_score_global, node_score_local, edge_index, edge_type, edge_length, local_edge_mask, kl_loss
        else:
            return pos_attr_global, pos_attr_local, node_score_global, node_score_local, edge_index, edge_type, edge_length, local_edge_mask,

**Comment by Layne-Huang** [comment]
> 代码写的太糟糕了，MDM_pocket_coor_shared.py 就不能把这个搞舒服点嘛？
> 
> ```
> '''
>     Atom numbers embedding
>     '''
>     if self.atom_num_emb:
>         context = context + num_node_ctx
> 
>     ligand_atom_feature = self.ligand_encoder(
>         node_attr=ligand_atom_type,
>         pos=ligand_pos,
>         batch=ligand_batch,
>     ) + context
>     # ligand_atom_feature = self.ligand_emblin(ligand_atom_type)+context
>     # protein_atom_feature = self.protein_emblin(protein_atom_feature)
>     ligand_atom_feature, protein_embeddings = self.atten_layer(ligand_atom_feature, protein_embeddings)
>     # ligand_atom_feature = self.atten_layer(ligand_atom_feature, protein_embeddings)
>     # ligand_atom_feature  = self.atten_layer(ligand_atom_feature, protein_atom_feature)
> 
>     pocket_atom = torch.cat([ligand_atom_feature, protein_embeddings], dim=0)
>     pocket_pos = torch.cat([ligand_pos, protein_pos], dim=0)
>     pocket_batch = torch.cat([ligand_batch, protein_batch])
>     pocket_mask = torch.cat([linker_mask,torch.zeros(protein_pos.size(0), dtype=torch.bool).to(linker_mask.device)]) if linker_mask is not None else None
> 
> 
> 
>     if edge_index is None or edge_type is None or edge_length is None:
>         full_bond_type = torch.ones(ligand_bond_index.size(1), dtype=torch.long).to(ligand_bond_index.device)
> 
>         # Construct local and global edges
>         edge_index, edge_type = extend_graph_order_radius(
>             num_nodes=N,
>             pos=ligand_pos,
>             edge_index=ligand_bond_index,
>             edge_type=full_bond_type,
>             batch=ligand_batch,
>             order=self.config.edge_order,
>             cutoff=self.config.cutoff,
>             extend_order=extend_order,
>             extend_radius=extend_radius,
>             is_sidechain=is_sidechain,
>         )
>         edge_length = get_distance(ligand_pos, edge_index).unsqueeze(-1)  # (E, 1)
>         ligand_bond_index = None #comment if fix the edge
> 
>     local_pocket_edge = get_edges(pocket_pos, pocket_batch, ligand_batch, self.config.cutoff, self.config.cutoff,ligand_bond_index) #ligand_bond_index
>     global_pocket_edge = get_edges(pocket_pos, pocket_batch, ligand_batch, self.config.g_cutoff,
>                                    self.config.g_cutoff)  # self.config.g_cutoff
>     local_pocket_edge_length = get_distance(pocket_pos, local_pocket_edge).unsqueeze(-1)
>     global_pocket_edge_length = get_distance(pocket_pos, global_pocket_edge).unsqueeze(-1)
> 
>     if ligand_bond_type is not None:
>         local_edge_mask = is_local_edge(ligand_bond_type)
>     else:
>         local_edge_mask = is_radius_edge(edge_type)
>     
>     
> 
>     # Emb time_step
>     # with the parameterization of NCSNv2
>     # DDPM loss implicit handle the noise variance scale conditioning
> 
>     # if self.time_emb:
>     #     # node2graph = ligand_batch
>     #     node2graph = pocket_batch
>     #     # edge2graph = node2graph.index_select(0, edge_index[0])
>     #     global_edge2graph = node2graph.index_select(0, global_pocket_edge[0])
>     #     g_temb_edge = temb.index_select(0, global_edge2graph)
>     #     g_protein_edge = protein_ctx.index_select(0, global_edge2graph)
>     #     # ptemb_edge = torch.cat([protein_edge,temb_edge],dim=1)
>     #     g_ptemb_edge = g_protein_edge+g_temb_edge
>     #     local_edge2graph = node2graph.index_select(0, local_pocket_edge[0])
>     #     l_temb_edge = temb.index_select(0, local_edge2graph)
>     #     l_protein_edge = protein_ctx.index_select(0, local_edge2graph)
>     #     # ptemb_edge = torch.cat([protein_edge,temb_edge],dim=1)
>     #     l_ptemb_edge = l_protein_edge+l_temb_edge
> 
>     # Encoding global
> 
>     # edge_attr_global = self.edge_encoder_global(
>     #     edge_length=edge_length,
>     #     edge_type=edge_type
>     # )   # Embed edges
>     edge_attr_global = self.edge_encoder_global(
>         edge_length=global_pocket_edge_length,
>         edge_type=None
>     )  # Embed edges
>     # if self.time_emb:
>     #     # edge_attr_global += temb_edge
>     #     edge_attr_global += g_ptemb_edge
> 
>     # # SphereNet
>     # _,node_attr_global,_ = self.encoder_global(
>     #     z=atom_type,
>     #     pos=pos,
>     #     batch=batch
>     # )
> 
>     # # SchNet
>     # # print(self.atom_type_input_dim)
>     # node_attr_global,pos_attr_global = self.encoder_global(
>     #     z=pocket_atom,
>     #     r=pocket_pos,
>     #     edge_index=global_pocket_edge,
>     #     edge_length=global_pocket_edge_length,
>     #     edge_attr=edge_attr_global,
>     #     ligand_batch=ligand_batch,
>     #     ctx=context,
>     #     embed_node = False # default is True
>     # )
> 
>     # EGNN
>     node_attr_global, pos_attr_global = self.encoder_global(
>         z=pocket_atom,
>         pos=pocket_pos,
>         edge_index=global_pocket_edge,
>         edge_attr=edge_attr_global,
>         batch=pocket_batch,
>         ligand_batch=ligand_batch,
>         context=context,
>         linker_mask=pocket_mask
>     )
> 
>     # Encoding local
>     # edge_attr_local = self.edge_encoder_local(
>     #     edge_length=edge_length,
>     #     edge_type=edge_type
>     # )   # Embed edges
>     edge_attr_local = self.edge_encoder_local(
>         edge_length=local_pocket_edge_length,
>         edge_type=None
>     )  # Embed edges
>     # if self.time_emb:
>     #     # edge_attr_local += temb_edge
>     #     edge_attr_local += l_ptemb_edge
> 
>     # # GIN
>     # node_attr_local = self.encoder_local(
>     #     z=ligand_atom_type,
>     #     edge_index=edge_index[:, local_edge_mask],
>     #     edge_attr=edge_attr_local[local_edge_mask],
>     # )
> 
>     # EGNN
>     node_attr_local, pos_attr_local = self.encoder_local(
>         z=pocket_atom,
>         pos=pocket_pos,
>         edge_index=local_pocket_edge,
>         edge_attr=edge_attr_local,
>         batch=pocket_batch,
>         ligand_batch=ligand_batch,
>         context=context,
>         linker_mask=pocket_mask
>     )
> 
>     # # Schnet
>     # node_attr_local, pos_attr_local = self.encoder_local(
>     #     z=pocket_atom,
>     #     r=pocket_pos,
>     #     edge_index=local_pocket_edge,
>     #     edge_length=local_pocket_edge_length,
>     #     edge_attr=edge_attr_local,
>     #     ligand_batch=ligand_batch,
>     #     ctx=context,
>     #     embed_node = False # default is True
>     # )
> 
>     node_score_global = self.grad_global_node_mlp(node_attr_global)
>     node_score_local = self.grad_local_node_mlp(node_attr_local)
> 
>     if self.vae_context:
>         return pos_attr_global, pos_attr_local, node_score_global, node_score_local, edge_index, edge_type, edge_length, local_edge_mask, kl_loss
>     else:
>         return pos_attr_global, pos_attr_local, node_score_global, node_score_local, edge_index, edge_type, edge_length, local_edge_mask,
> ```

Hi,

Sorry about the inconvenience caused. We are actively working on PMDM to extend its applications, and the current release is an initial version. We will finalize the development and improve the code formatting soon. Thank you for your patience and understanding.

**Comment by maple0leaves** [comment]
![image](https://github.com/user-attachments/assets/800f24c3-25d0-4f8b-ae51-5908662d640a)
Hi,I also encountered the same problem,I didn't change any arguments of crossdock_epoch.yml，just run "python -u train.py --config configs/crossdock_epoch.yml"

**Comment by maple0leaves** [comment]
@Bigrock-dd Hi,Do you know how to fix this bug? I would be grateful if you could give me some tips，Thank you!

**Comment by maple0leaves** [comment]
@DrugD Thank you very much!
