### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.sample'

### ISSUE THREAD

**Issue by MKCarter** [Layne-Huang/PMDM#4]
Hi,

I have installed the code and setup the environment, but it appears that their is an issue with importing the utilities from `sample.py` into the other scripts:

When I run:
```
python sample_for_pdb.py -h
Traceback (most recent call last):
  File "/home/michaelcarter/DD_tools/PMDM/sample_for_pdb.py", line 20, in <module>
    from utils.sample import *
ModuleNotFoundError: No module named 'utils.sample
```
This error persists for all scripts... do you have a fix for this?

**Comment by Layne-Huang** [comment]
Thanks for your interest! I have uploaded the sample.py file. Please let me know if there is any further issue.
