### ISSUE TITLE
Need sampled molecules

### ISSUE THREAD

**Issue by explorer1212** [Layne-Huang/PMDM#42]
Hello, Could you provide the sampled molecules? Thank you!

**Comment by Layne-Huang** [comment]
Hi,

What do you mean the sampled molecules?

**Comment by explorer1212** [comment]
Thanks for your reply! 
The sampled molecules are the molecules you used to evaluate the model capabilities, such as vina score, High Affinity

**Comment by Layne-Huang** [comment]
The generated molecules have already been put into Zenodo.
