### ISSUE TITLE
Missing File for training 

### ISSUE THREAD

**Issue by kskim-phd** [Layne-Huang/PMDM#6]
Dear Author,
I sincerely thank you for your great work.
Could you please add train.py to the utils folder? 
It was missed in the current repo. Thank you!

**Comment by Layne-Huang** [comment]
Hi,

Thanks for your interests! Sorry for the missing file. We have uploaded the corresponding file. Please check it.

**Comment by OlfwayAdbayIgbay** [comment]
@Layne-Huang The models folder is missing in Zenodo, is this intentional or is zenodo outdated?

**Comment by Layne-Huang** [comment]
Hi, sorry for the late response. We have added another link for the model weights: https://drive.google.com/file/d/1Zn8KbumzQ5S_Rc6lb4ezVvydgTeHjzbI/view?usp=drive_link
